# Generated by Django 4.0.4 on 2022-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElektronKitabxana', '0005_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('middleName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('photo', models.ImageField(null=True, upload_to='authors')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
