# Generated by Django 4.0.4 on 2022-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElektronKitabxana', '0006_author_remove_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='middleName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
