# Generated by Django 4.0.4 on 2022-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElektronKitabxana', '0019_alter_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
