# Generated by Django 4.0.4 on 2022-04-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElektronKitabxana', '0020_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ElektronKitabxana.author'),
        ),
    ]
